version: "3.3"
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
 
services:
    apache:
        container_name: ${COMPOSE_PROJECT_NAME}_apache
        build:
            context: docker/apache
            args:
                - APACHE_IMG_VERSION=${APACHE_IMG_VERSION}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        volumes:
            - ./docker/apache/log:${APACHE_ROOT_DIR}/logs
            - ./docker/apache/conf/httpd.conf:${APACHE_ROOT_DIR}/conf/httpd.conf:ro
            - ./docker/apache/conf/httpd-vhosts.conf:${APACHE_ROOT_DIR}/conf/extra/httpd-vhosts.conf:ro
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        networks:
            public_net:
                ipv4_address: ${APACHE_IP}
        env_file:
            - .env

    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        build:
            context: docker/php
            args:
                - PHP_IMG_VERSION=${PHP_IMG_VERSION}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        working_dir: ${PHP_APP_DIR}
        volumes:
            - ./public:${PHP_APP_DIR}
            - ./docker/php/log:${PHP_ROOT_DIR}/logs
            - ./docker/php/conf/www.conf:${PHP_ROOT_DIR}/php-fpm.d/www.conf:ro
        depends_on:
            - apache
            - db
        networks:
            public_net:
                ipv4_address: ${PHP_IP}
        env_file:
            - .env

    db:
        container_name: ${COMPOSE_PROJECT_NAME}_mariadb
        build:
            context: docker/mariadb
            args:
                - MARIADB_IMG_VERSION=${MARIADB_IMG_VERSION}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - MARIADB_CONTAINER_USER=${MARIADB_CONTAINER_USER}
                - MARIADB_CONTAINER_GROUP=${MARIADB_CONTAINER_GROUP}
        volumes:
            - ./docker/mariadb/log:${MARIADB_LOG_DIR}
            - ./docker/mariadb/data:${MARIADB_DATA_DIR}
            # Peut être pas indispensable
            - .docker/mariadb/dump:/docker-entrypoint-initdb.d
            # La conf a revoir
            - .docker/mariadb/conf/esco-server.cnf:/etc/mysql/conf.d/custom.cnf:ro
            - /etc/timezone:/etc/timezone:ro
        networks:
            public_net:
                ipv4_address: ${MARIADB_IP}
        env_file:
            - .env
        command: 'mysqld --innodb-flush-method=fsync'
        # A voir si utile
        healthcheck:
            test: "cat /proc/net/tcp /proc/net/tcp6 | grep ':0CEA'"
            interval: 10s
            timeout: 5s
            retries: 5

    adminer:
        container_name: ${COMPOSE_PROJECT_NAME}_adminer
        image: adminer
        networks:
            public_net:
                ipv4_address: ${ADMINER_IP}
        restart: always
        ports:
            - ${ADMINER_EXPOSED_PORT}:8080
        env_file:
            - .env
        links:
            - db:${COMPOSE_PROJECT_NAME}_mariadb