version: "3.3"
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
 
services:
    apache:
        container_name: ${COMPOSE_PROJECT_NAME}_apache
        build:
            context: docker/apache
            args:
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        volumes:
            - ./docker/apache/log:${APACHE_ROOT_DIR}/logs
            - ./docker/apache/conf/httpd.conf:${APACHE_ROOT_DIR}/conf/httpd.conf:ro
            - ./docker/apache/conf/httpd-vhosts.conf:${APACHE_ROOT_DIR}/conf/extra/httpd-vhosts.conf:ro
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        networks:
            public_net:
                ipv4_address: ${APACHE_IP}
        env_file:
            - .env

    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        build:
            context: docker/php
            args:
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        working_dir: ${PHP_APP_DIR}
        volumes:
            - .:${PHP_APP_DIR}
            - ./docker/php/log:${PHP_ROOT_DIR}/logs
            - ./docker/php/conf/www.conf:${PHP_ROOT_DIR}/php-fpm.d/www.conf:ro
        depends_on:
            - apache
            - mysql
        networks:
            public_net:
                ipv4_address: ${PHP_IP}
        env_file:
            - .env

    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        build:
            context: docker/mysql
            args:
                - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
                - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
        volumes:
            - ./docker/mysql/log:${MYSQL_LOG_DIR}
            - ./docker/mysql/data:${MYSQL_DATA_DIR}
        networks:
            public_net:
                ipv4_address: ${MYSQL_IP}
        environment:
            - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
            - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}